### ISSUE TITLE
How to completely remove?

### ISSUE THREAD

**Issue by Andrew-H2O** [Brandawg93/Pi-Hole-Monitoring#11]
Can you provide some uninstallation instructions, please?

**Comment by Brandawg93** [comment]
`docker-compose down`

**Comment by Andrew-H2O** [comment]
That just stops docker, though.  It doesn't remove either docker or the containers or images.

**Comment by Brandawg93** [comment]
Remove all docker images: `docker system prune -a`
[Uninstalling docker](https://askubuntu.com/questions/935569/how-to-completely-uninstall-docker).
