### ISSUE TITLE
Possibility to send data to separate influxdb?

### ISSUE THREAD

**Issue by klausagnoletti** [Brandawg93/Pi-Hole-Monitoring#12]
Hi

I want to install this on my rpi with pi-hole in a docker. I have influxdb and grafana running on a 'real' server in my network. Is it possible to use this in that scenario using (I guess) telegraf running locally along with your pi-hole db parsing code? If so, how?

Thanks!

/klaus

**Comment by Brandawg93** [comment]
The telegraf part should work just fine like it is. The db parsing tool will need to be tweaked to point to your externally available influxdb. It will need to be run local to the pi-hole instance.

**Comment by Brandawg93** [comment]
I've added environment variables to be able to send data to an external influxdb.
