### ISSUE TITLE
No data points @ top ads by domain/queries

### ISSUE THREAD

**Issue by AeonEternum** [Brandawg93/Pi-Hole-Monitoring#15]
Hi!

Not sure whether you're able to help out here too, but I'll give it a shot.

Followed your guide, everything setup correctly as it seems, dashboards are working and data is coming in.

What's not working:
![image](https://user-images.githubusercontent.com/48135512/89005662-4ee2b900-d305-11ea-8092-37eaeac30067.png)

Every other graph displays data as intended.

Did I miss something? Any pointers?

Thanks!

Cheers,
Aeon

**Comment by Brandawg93** [comment]
This is usually an indication that the server running this cannot reach http://pi.hole/admin. Try running the container using `docker-compose up` (without the -d) to see what errors it is throwing.

**Comment by Brandawg93** [comment]
I've added an [environment variable](https://github.com/Brandawg93/Pi-Hole-Monitoring/blob/master/docker-compose.yml#L27) to allow you to manually specify the location of your pi. If you cannot reach http://pi.hole/admin, try changing that line of code to the pihole instance ip address directly.

**Comment by AeonEternum** [comment]
Now it's working after I exchanged the dns name for the IP. Thank you @Brandawg93
