### ISSUE TITLE
Pi Hole dashboard not working

### ISSUE THREAD

**Issue by flow23** [Brandawg93/Pi-Hole-Monitoring#17]
Hi,
the following graphs in the Pi Hole dashboard are not working:

- Status
- DNS Queries
- Number Of Blocked Queries
- Blocked %age
- Domains on Blocklist
- Cached DNS Queries
- Realtime Queries
- Realtime Replies

The other ones  are working.

**Comment by Brandawg93** [comment]
This is expected if the monitoring program cannot connect to the `pihole-FTL.db`.

**Comment by flow23** [comment]
Okay, how can I troubleshoot this?

**Comment by Brandawg93** [comment]
Try running the program without the `-d`. That will give you all the output of the program. There will be an error with `sql_influx`.

**Comment by flow23** [comment]
Hi,
I nailed it down to 
`telegraf      | 2020-08-02T18:32:50Z E! [inputs.http] Error in plugin: [url=http://pi.hole/admin/api.php]: Get "http://pi.hole/admin/api.php": dial tcp: lookup pi.hole on 127.0.0.11:53: no such host`
I'm not sure where the IP 127.0.0.11 comes from. But the url is reachable in my network, here is the feedback:
```
{
"domains_being_blocked": 85314,
"dns_queries_today": 28375,
"ads_blocked_today": 1076,
"ads_percentage_today": 3.79207,
"unique_domains": 1435,
"queries_forwarded": 9526,
"queries_cached": 17773,
"clients_ever_seen": 14,
"unique_clients": 14,
"dns_queries_all_types": 28375,
"reply_NODATA": 0,
"reply_NXDOMAIN": 8,
"reply_CNAME": 38,
"reply_IP": 25,
"privacy_level": 0,
"status": "enabled",
"gravity_last_updated": {
"file_exists": true,
"absolute": 1596338109,
"relative": {
"days": 0,
"hours": 15,
"minutes": 18
}
}
}
```

**Comment by flow23** [comment]
I changed the environment variable to my IP address and it works.
That's fine for me.
```
    environment:
      - PIHOLE_API_URL=http://10.0.1.xx/admin/api.php
```
