### ISSUE TITLE
Pi Hole Monitoring dashboard shows N/A for 5 fields

### ISSUE THREAD

**Issue by suhasa010** [Brandawg93/Pi-Hole-Monitoring#19]
![image](https://user-images.githubusercontent.com/11756922/95019294-2d45db00-0682-11eb-97dd-78812c4774e0.png)

All other fields are working fine and shows correct data. am i doing something wrong here?

**Comment by Brandawg93** [comment]
> You need to be able to view the Pi-Hole admin page at http://pi.hole/admin.

I think this may be your issue. If the device running this cannot reach pi hole via the link above, then it cannot generate those graphs.

**Comment by suhasa010** [comment]
I am able to view both pi.hole/admin and via 192.168.31.105:3000. Not sure what's wrong.

**Comment by Brandawg93** [comment]
You may need to enable the api in pi hole. http://pi.hole/admin/api.php

**Comment by suhasa010** [comment]
```
{"domains_being_blocked":972468,"dns_queries_today":29048,"ads_blocked_today":12059,"ads_percentage_today":41.514046,"unique_domains":2292,"queries_forwarded":14395,"queries_cached":1917,"clients_ever_seen":2,"unique_clients":2,"dns_queries_all_types":29048,"reply_NODATA":127,"reply_NXDOMAIN":48,"reply_CNAME":1898,"reply_IP":6057,"privacy_level":0,"status":"enabled","gravity_last_updated":{"file_exists":true,"absolute":1601845258,"relative":{"days":0,"hours":3,"minutes":41}}}
```

This means that it's active right? 🤔

**Comment by Brandawg93** [comment]
Correct. That looks good. It could also be the graphs in grafana. They display data over time. If it hasn't been running for long, then it may take some time for enough data to populate.

**Comment by suhasa010** [comment]
It's been active since 6-8 hours now. I'll wait for some more time then and report back. Thanks.

**Comment by Brandawg93** [comment]
Ok. Make sure grafana isn't set to 24h in the top right. If it hasn't been 24 hours yet, then that could be it.

**Comment by suhasa010** [comment]
It is set to 30seconds btw.

Oh wait, is it because I've enabled log2ram + zram?
Maybe it isn't able to fetch the logs because there isn't any. It's all in the RAM.

**Comment by Brandawg93** [comment]
That's a possibility. IIRC, log2ram only writes once every 24 hours to disk.

**Comment by suhasa010** [comment]
> That's a possibility. IIRC, log2ram only writes once every 24 hours to disk. 

Yep. Thanks again.

**Comment by suhasa010** [comment]
After 2 days it's the same, unfortunately. But I guess it is because of the logs being logged in RAM.
