### ISSUE TITLE
Unusually high memory usage by influxd

### ISSUE THREAD

**Issue by suhasa010** [Brandawg93/Pi-Hole-Monitoring#20]
Almost 55.9% of memory being used by Grafana dashboard. is this normal?

![image](https://user-images.githubusercontent.com/11756922/95502673-cc8f0900-09c7-11eb-935b-02609a808d77.png)

**Comment by Brandawg93** [comment]
Are you using log2ram?

**Comment by suhasa010** [comment]
> Are you using log2ram?

yes. i am the same guy who raised the earlier issue. should i just remove log2ram so that i don't face such issues?

**Comment by Brandawg93** [comment]
That would be my suggestion if you are using anything with telegraf/influxdb.

**Comment by suhasa010** [comment]
> That would be my suggestion if you are using anything with telegraf/influxdb.

thanks. i am removing it now.
