### ISSUE TITLE
Influxdb 1.8.4 (or any below) fatal error: out of memory

### ISSUE THREAD

**Issue by vgeorgiev69** [Brandawg93/Pi-Hole-Monitoring#32]
Not sure if you are planning to upgrade this, but with recent updates of influxdb, there's a massive memory usage which crashes the influxdb. It's an influxdb "Bug that potentially increased memory usage was introduced in 1.8.1. If you installed this release, install v1.8.2, which includes the features, performance improvements, and bug fixes below"

Using :latest completely doesn't work, because 2.x doesn't support 32-bit OS. Using 1.7 and every 1.8.x version breaks with "runtime: out of memory: cannot allocate 8192-byte block (896204800 in use)"

I've been using your monitoring for 2 years already and it was working flawlessly until i did an update :/

**Comment by Brandawg93** [comment]
I actually looked into this some time ago and found 2 not very good solutions:

1. Update influxdb to 2.X and force everyone not running an x64 build of raspbian to wipe their devices and update. 

2. Switch to something like [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics) and completely redo the code. 

Neither are great solutions, but I haven't found anything better...

**Comment by vgeorgiev69** [comment]
Thanks for the response, appreciated! I'll give them a try. 
Are you planning on expanding this project or doing any similar to this one?

**Comment by Brandawg93** [comment]
I do not have any immediate plans to update this project, but I welcome pull requests with new features.
