### ISSUE TITLE
Issue with basic Pihole stats

### ISSUE THREAD

**Issue by NossieUK** [Brandawg93/Pi-Hole-Monitoring#35]
Just wondering if anyone else is having this issue.

I'm just running pihole on unbound with this setup and I'm getting this on grafana?

![image](https://user-images.githubusercontent.com/93691973/141194712-5a687401-f76b-4fe7-846d-a7ff52c506c4.png)

**Comment by Brandawg93** [comment]
You may need to change "pi.hole/" to the actual ip address of the pi in the `docker-compose.yml`.

**Comment by NossieUK** [comment]
nevermind, let me try that.....

**Comment by NossieUK** [comment]
That worked great, thank you very much - only status is now N/A but I can live with that :)

**Comment by Brandawg93** [comment]
Great! Mine shows N/A as well. Its something with a recent pihole update. You can watch this repo and will be notified when I fix it.
