### ISSUE TITLE
ERROR: Service 'sql_influx' failed to build : Build failed

### ISSUE THREAD

**Issue by oscardobsonbrown** [Brandawg93/Pi-Hole-Monitoring#36]
Hello, I just tried installing but when I get to the last step of running the command `sudo docker-compose up -d` I am greeted with this error message
`Building sql_influx
Sending build context to Docker daemon  8.192kB
Step 1/4 : FROM python:3-alpine
 ---> cb9adba83420
Step 2/4 : COPY ./requirements.txt .
 ---> Using cache
 ---> 08d7600abad7
Step 3/4 : RUN pip install -r requirements.txt
 ---> Running in 2edf1233b0de
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/__init__.py", line 4, in <module>
    from pip._internal.utils import _log
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/utils/_log.py", line 8, in <module>
    import logging
  File "/usr/local/lib/python3.10/logging/__init__.py", line 57, in <module>
    _startTime = time.time()
PermissionError: [Errno 1] Operation not permitted
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
ERROR: Service 'sql_influx' failed to build : Build failed`

I am running this on a Raspberry Pi and changed the "python" command to use 3.10 instead of 2.7 because it was giving me grief with a previous command in the instructions

**Comment by Brandawg93** [comment]
It looks like you're running into a permission error. Make sure that you have a proper permissions for the folder you are using and maybe try "sudo" although that isn't a great long term solution.

**Comment by oscardobsonbrown** [comment]
I found another thread which reported the same issue as me. I changed line 1 in `Dockerfile` in `/home/pi/Pi-Hole-Monitoring/sql_influx` from `FROM python3 alpine` to buster.

The error is now that <ip address>:3000 bind is in use. 

I'll try to change the current grafana port to see if that's the issue

**Comment by Brandawg93** [comment]
Good to hear! If you run into anything else just let me know.

**Comment by oscardobsonbrown** [comment]
It's all fixed, I was running a grafana process from a previous tutorial I went though
