### ISSUE TITLE
Unable to start docker compose.

### ISSUE THREAD

**Issue by bartvad3r** [Brandawg93/Pi-Hole-Monitoring#38]
Hi after I followed all the instructions and got to the step to launch docker compose. Unfortunately I keep getting the error bellow, I tried to Google the issue but so far I'm unable to find another user with a similar issue. I am attempting this  on a Raspberry Pi 4 running Raspbian Buster. Thanks in advance for your assistance. 

Step 3/4 : RUN pip install -r requirements.txt
 ---> Running in b31becf508a6
Fatal Python error: init_interp_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0xb6fe7390 (most recent call first):
<no Python frame>
ERROR: Service 'sql_influx' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1

**Comment by Brandawg93** [comment]
That seems to be an issue with your python setup.
