### ISSUE TITLE
Not getting real time data

### ISSUE THREAD

**Issue by t33j-sec** [Brandawg93/Pi-Hole-Monitoring#40]
Any ideas on why I would not be getting real time data like queries and replies?

**Comment by rdheepak** [comment]
Same question here. 
Do I need to wait for a certain period of time for this data to get populated?
The current dashboards look like the attached image.
<img width="840" alt="chrome_2022_06_14_00213" src="https://user-images.githubusercontent.com/68311845/173587731-86f89d14-e5cc-4833-88f0-08ca8a12f205.png">

**Comment by Brandawg93** [comment]
It could be an issue with the sql_influx container. You may want to check it for errors.
