### ISSUE TITLE
/etc/grafana/grafana.ini not found causing grafana to restart constantly

### ISSUE THREAD

**Issue by sat22** [Brandawg93/Pi-Hole-Monitoring#8]
Following instructions and everything seems to be installed, but I can't connect to port 3000.  So I ran docker-compose up so I could see what was going on and I see this:

Starting influxdb ... done
Starting sql_influx ... done
Starting grafana    ... done
Starting telegraf   ... done
Attaching to influxdb, sql_influx, grafana, telegraf
grafana       | GF_PATHS_CONFIG='/etc/grafana/grafana.ini' is not readable.
grafana       | You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
telegraf      | 2019-12-23T18:18:40Z I! Starting Telegraf 1.13.0
telegraf      | 2019-12-23T18:18:40Z I! Using config file: /etc/telegraf/telegraf.conf
telegraf      | 2019-12-23T18:18:40Z I! Loaded inputs: diskio http disk kernel mem processes swap system exec cpu
telegraf      | 2019-12-23T18:18:40Z I! Loaded aggregators:
telegraf      | 2019-12-23T18:18:40Z I! Loaded processors:
telegraf      | 2019-12-23T18:18:40Z I! Loaded outputs: influxdb
telegraf      | 2019-12-23T18:18:40Z I! Tags enabled: host=6d1cd3fd048f
telegraf      | 2019-12-23T18:18:40Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"6d1cd3fd048f", Flush Interval:10s
telegraf      | 2019-12-23T18:18:40Z W! [outputs.influxdb] When writing to [http://influxdb:8086]: database "telegraf" creation failed: Post http://influxdb:8086/query: dial tcp 172.19.0.2:8086: connect: connection refused
sql_influx    | Could not connect. Retrying...
grafana       | installing grafana-piechart-panel @ 1.3.9
grafana       | from: https://grafana.com/api/plugins/grafana-piechart-panel/versions/1.3.9/download
grafana       | into: /var/lib/grafana/plugins
grafana       |
grafana       | ✔ Installed grafana-piechart-panel successfully
grafana       |
grafana       | Restart grafana after installing plugins . <service grafana-server restart>
grafana       |
grafana       | t=2019-12-23T18:18:41+0000 lvl=crit msg="Failed to parse /etc/grafana/grafana.ini, open /etc/grafana/grafana.ini: no such file or directory"
grafana       | installing grafana-piechart-panel @ 1.3.9
grafana       | from: https://grafana.com/api/plugins/grafana-piechart-panel/versions/1.3.9/download
grafana       | into: /var/lib/grafana/plugins
grafana       |
grafana       | ✔ Installed grafana-piechart-panel successfully
grafana       |
grafana       | Restart grafana after installing plugins . <service grafana-server restart>
grafana       |
grafana       | t=2019-12-23T18:18:43+0000 lvl=crit msg="Failed to parse /etc/grafana/grafana.ini, open /etc/grafana/grafana.ini: no such file or directory"
grafana exited with code 1
grafana       | installing grafana-piechart-panel @ 1.3.9
grafana       | from: https://grafana.com/api/plugins/grafana-piechart-panel/versions/1.3.9/download
grafana       | into: /var/lib/grafana/plugins
grafana       |
sql_influx    | Could not connect. Retrying...
grafana       | ✔ Installed grafana-piechart-panel successfully
grafana       |
grafana       | Restart grafana after installing plugins . <service grafana-server restart>
grafana       |
grafana       | t=2019-12-23T18:18:45+0000 lvl=crit msg="Failed to parse /etc/grafana/grafana.ini, open /etc/grafana/grafana.ini: no such file or directory"
grafana exited with code 1
influxdb      | ts=2019-12-23T18:18:46.982362Z lvl=info msg="InfluxDB starting" log_id=0Jt~_7HW000 version=1.7.9 branch=1.7 commit=23bc63d43a8dc05f53afa46e3526ebb5578f3d88
...

repeat ad naseum

Any ideas?

**Comment by Brandawg93** [comment]
I was working on some other changes. I've reverted now. Do a pull and try again. It should be working.

**Comment by sat22** [comment]
I pulled and it seems to be mostly working.  The following items have no data or are N/A:

Status
DNS Queries
Number of Blocked Queries
Blacked %age
Domains on Blocklist
Cached DNS Queries
Realtime Queries
Realtime Replies

All the rest have data.

If this is unrelated, I can troubleshoot some more or open a new issue.

**Comment by sat22** [comment]
I pulled and it seems to be mostly working. The following items have no data or are N/A:

Status
DNS Queries
Number of Blocked Queries
Blacked %age
Domains on Blocklist
Cached DNS Queries
Realtime Queries
Realtime Replies

All the rest have data.

If this is unrelated, I can troubleshoot some more or open a new issue.

**Comment by Brandawg93** [comment]
#5
