### ISSUE TITLE
Error installing inflixdb on Pi Zero

### ISSUE THREAD

**Issue by mkm29** [Brandawg93/Pi-Hole-Monitoring#9]
I followed the readme to a tee and cannot get it installed on my Pi Zero W, I first ran an `apt-get update && apt-get upgrade` I get the following: ERROR: Service 'sql_influx' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 139

However, running pip install -r requirements.txt works fine.

**Comment by Brandawg93** [comment]
#6
